# docker/Dockerfile.telegram
FROM python:3.9-slim

WORKDIR /notifier

COPY ./tg_notifier /notifier
COPY requirements.txt /notifier/requirements.txt

RUN pip install --upgrade pip && pip install -r requirements.txt

CMD ["python", "main.py"]
